### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mperham** [contribsys/faktory#1]
## Core runtime

- [x] Ensure all operations to be atomic within DB.
- [x] Blocking semantics on POP

## Tooling

- [ ] RPM/DEB packages
- [ ] Add benchmark/load testing script

## Web UI 

- [x] Implement retry UI
- [x] Implement scheduled UI
- [x] Implement dead UI
- [x] Implement busy UI
- [x] Port over i18n translations
- [x] Test for each UI page

## Launch

- [x] Pre blog post
- [x] ANN blog post
- [ ] Homepage
- [x] Wiki docs
