### ISSUE TITLE
Initial commercial roadmap

### ISSUE THREAD

**Issue by mperham** [contribsys/faktory#112]
What features will commercial versions of Faktory contain?  Keep in mind that all of this is still subject to change.  Candidates and initial plan:

## Faktory Pro

* [x] Expiring Jobs
* [ ] Job Metrics via Statsd
* [x] Periodic Jobs
* [x] Redis Gateway (expose Redis port for real-time replication/HA)

## Faktory Enterprise

* [ ] Queue Throttling (no more than X jobs per Y, or more than Z concurrently)
* [ ] Batches/Workflows
* [ ] Unique Jobs
* [ ] Web UI Search
* [ ] Web UI authorization/SSO integration

**Comment by cdrx** [comment]
Not sure how this works with Sidekiq pro, but do you expect pro or enterprise to come with source access?

**Comment by mperham** [comment]
Sidekiq Pro does not give access to the source repos but the gem file does include the source since it's just normal Ruby code.

I would expect Faktory Pro to not include source access by default but the license will definitely have a clause where the code will be open sourced should the company no longer be able to continue (i.e. the "hit by a bus" clause).  Of course everything is negotiable if a larger company wants a larger license including source access.  I would imagine Faktory SaaSes would negotiate source access as part of offering Faktory Pro/Enterprise to their customers.

**Comment by mperham** [comment]
I should also note that any Faktory committer who is also a customer will generally get repo access to the corresponding commercial repo also.  If you've proven to be helpful with Faktory, I definitely want the same feedback/POV for the other repos.  I have a few Sidekiq committers who enjoy reviewing my commercial commits and have proven to be invaluable in catching bugs and feature edge cases.

**Comment by bronislav** [comment]
hi @mperham, any updates on this roadmap?

**Comment by mperham** [comment]
@bronislav None.

**Comment by mperham** [comment]
I plan to launch Faktory Pro this quarter.  As you can see from the feature list above, much of the initial work to build the functionality is complete.  Current plan is to release Faktory 0.9 with the new Redis storage and then have an initial Faktory Pro beta period where it will be free to try but time limited (e.g. won't work after 1Q19).  Faktory 1.0 and Faktory Pro 1.0 will launch soon after.

**Comment by jnylen** [comment]
@mperham,
Do you have any pricing info for Pro and Enterprise?

**Comment by mperham** [comment]
Faktory Pro is now available for $149/mo for the first production server, $49/mo for each additional server. Development servers are free and unlimited.  I'll create more specific issues for further improvements and features as I start planning them.
