### ISSUE TITLE
Job Status and Tracking

### ISSUE THREAD

**Issue by mperham** [contribsys/faktory#278]
Implement job status and tracking.

* [x] Tracking - get the current state for a given JID: enqueued, working, failed, success, etc.
* [x] Status - get a percentage and description of a working job's current progress
* [ ] Web UI to view the set of current working jobs
* [x] Update Go and Ruby client APIs with new commands
* [x] [Wiki page documentation](/contribsys/faktory/wiki/Ent-Tracking)

Per #272

**Comment by scottrobertson** [comment]
@mperham as part of this, or a future update, could you maybe add the last known job status to the cron history page too?

**Comment by mperham** [comment]
I can't because Job Tracking is part of Enterprise, cron is part of Pro.

**Comment by scottrobertson** [comment]
What about allowing it for ent customers?

Or does that complicate things a lot?

**Comment by mperham** [comment]
yeah, exactly, it complicates things greatly. I'm not against it but I need to see more customer demand over time before I'm willing to add that complexity.

**Comment by scottrobertson** [comment]
@mperham did this not make 1.3?

**Comment by mperham** [comment]
90% made it in 1.3.  I was not able to settle on a good Web UI so there is no UI for it, API only today.

**Comment by scottrobertson** [comment]
@mperham no problem. Will there be an API in the ruby client to get the status, so that we can implement it on our own for now?

**Comment by mperham** [comment]
Crap, I forgot to merge the branch.  It's not in 1.3.0.

**Comment by scottrobertson** [comment]
No problem :D

**Comment by mperham** [comment]
Let's give 1.3.0 a few days (in case other people find other issues) and I'll turn a 1.3.1 or 1.4 release next week with tracking merged. Really disappointed in myself here, thanks for your patience.

**Comment by scottrobertson** [comment]
No problem at all! Will roll 1.3.0, although i think we have most of it running already yeah?

**Comment by mperham** [comment]
Yep, it should have fixes for the various issues you raised.

**Comment by scottrobertson** [comment]
Any news on this @mperham. 

Trying to debug a long running job issue, and this would be super useful right now.
